apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "vpn.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "vpn.name" . }}
    helm.sh/chart: {{ include "vpn.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  capacity:
    storage: 500Gi
  accessModes:
  - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /lib/modules
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - randomstore
          - random
