apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "vpn.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "vpn.name" . }}
    helm.sh/chart: {{ include "vpn.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  capacity:
    storage: 500Gi
  accessModes:
  - ReadOnlyMany
  storageClassName: local-storage
  resources:
    requests:
      storage: 3Gi
